<?php

/**
 * Copyright [2019] New Relic Corporation. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file contains the tests for the New Relic Monolog Enricher
 * Handler.
 *
 * @author New Relic PHP <php-agent@newrelic.com>
 */

namespace NewRelic\Monolog\Enricher;

use CurlHandle;
use DateTimeImmutable;
use Monolog\Formatter\NormalizerFormatter;
use Monolog\Handler\MissingExtensionException;
use Monolog\Level;
use Monolog\LogRecord;
use PHPUnit\Framework\TestCase;

class HandlerTest extends TestCase
{
    public function setUp(): void
    {
        $GLOBALS['extension_loaded'] = true;
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public static function defaultHostProvider(): array
    {
        return array(
            'normal eu key' => array(
                'eu01xx0000000000000000000000000000000000',
                'log-api.eu.newrelic.com',
            ),
            'normal us key' => array(
                '0000000000000000000000000000000000000000',
                'log-api.newrelic.com',
            ),
            'malformed key without a region identifier' => array(
                'x000000000000000000000000000000000000000',
                'log-api.newrelic.com',
            ),
            'key with a region identifier that is too long' => array(
                'abcd00x000000000000000000000000000000000',
                'log-api.newrelic.com',
            ),
            'key with a region identifier that is too short' => array(
                'a00x000000000000000000000000000000000000',
                'log-api.newrelic.com',
            ),
            'empty key' => array(
                '',
                'log-api.newrelic.com',
            ),
        );
    }

    public static function defaultHostExceptionProvider(): array
    {
        return array(
            'non-string key' => array(
                array(),
                'InvalidArgumentException',
            ),
            'null key' => array(
                null,
                'InvalidArgumentException',
            ),
        );
    }

    public function testHandle()
    {
        $record = new LogRecord(
            new DateTimeImmutable("now", new \DateTimeZone("UTC")),
            'test',
            Level::Warning,
            'test',
            [],
            [],
        );

        $formatter = new Formatter(Formatter::BATCH_MODE_JSON, false);
        $expected = $formatter->format($record);
        $this->expectOutputString($expected);
        $handler = new StubHandler();
        $handler->handle($record);
    }

    public function testHandleBatch()
    {
        $record = new LogRecord(
            new DateTimeImmutable("now", new \DateTimeZone("UTC")),
            'test',
            Level::Warning,
            'test',
            [],
            [],
        );

        $formatter = new Formatter(Formatter::BATCH_MODE_JSON, false);
        $expected = $formatter->formatBatch(array($record));
        $this->expectOutputString($expected);
        $handler = new StubHandler();
        $handler->handleBatch(array($record));
    }

    public function testSetFormatter()
    {
        $handler = new Handler();
        $formatter = new Formatter();
        $handler->setFormatter($formatter);
        $this->assertInstanceOf(
            Formatter::class,
            $handler->getFormatter()
        );
    }

    public function testDefaultFormatterConfig()
    {
        $handler = new Handler();
        $formatter = $handler->getFormatter();
        $this->assertEquals(
            Formatter::BATCH_MODE_JSON,
            $formatter->getBatchMode()
        );
        $this->assertEquals(false, $formatter->isAppendingNewlines());
    }

    public function testSetFormatterInvalid()
    {
        $handler = new Handler();
        $formatter = new NormalizerFormatter();

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage(
            'NewRelic\Monolog\Enricher\Handler is only compatible with '
            . 'NewRelic\Monolog\Enricher\Formatter'
        );

        $handler->setFormatter($formatter);
    }

    public function testMissingCurlExtension()
    {
        $this->expectException(MissingExtensionException::class);
        $this->expectExceptionMessage(
            'The curl extension is required to use this Handler'
        );

        $GLOBALS['extension_loaded'] = false;
        $handler = new Handler();
        $GLOBALS['extension_loaded'] = true;
    }

    public function testCurlHandlerExplicitHost()
    {
        $handler = new StubHandler();
        $handler->setHost('foo.bar');

        $ch = $handler->getCurlHandler();

        $url = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);
        $parts = parse_url($url);

        $this->assertSame('https', $parts['scheme']);
        $this->assertSame('foo.bar', $parts['host']);
        $this->assertSame($handler->getEndpoint(), substr($parts['path'], 1));
    }

    /**
     * @dataProvider defaultHostProvider
     */
    public function testCurlHandlerDefault($key, $expected)
    {
        $handler = new StubHandler();
        $handler->setLicenseKey($key);

        $ch = $handler->getCurlHandler();

        $url = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);
        $parts = parse_url($url);

        $this->assertSame('https', $parts['scheme']);
        $this->assertSame($expected, $parts['host']);
        $this->assertSame($handler->getEndpoint(), substr($parts['path'], 1));
    }

    /**
     * @dataProvider defaultHostExceptionProvider
     */
    public function testCurlHandlerDefaultException($key, $expectedException)
    {
        $this->expectException($expectedException);

        $handler = new StubHandler();
        $handler->setLicenseKey($key);
        $handler->getCurlHandler();
    }

    /**
     * @dataProvider defaultHostProvider
     */
    public function testDefaultHost($key, $expected)
    {
        $this->assertSame($expected, StubHandler::getDefaultHost($key));
    }

    /**
     * @dataProvider defaultHostExceptionProvider
     */
    public function testDefaultHostException($key, $expectedException)
    {
        $this->expectException($expectedException);
        StubHandler::getDefaultHost($key);
    }
}

// phpcs:disable

/**
 * Stubhandler overrides the methods of Handler that normally call
 * curl_exec, and instead outputs the data they receive.
 *
 * It also exports a couple of normally protected methods as public for
 * easier testing.
 */
class StubHandler extends Handler
{
    static public function getDefaultHost($licenseKey): string
    {
        return parent::getDefaultHost($licenseKey);
    }

    public function getCurlHandler(): CurlHandle
    {
        return parent::getCurlHandler();
    }

    public function getEndpoint()
    {
        return $this->endpoint;
    }

    protected function send($data): void
    {
        print($data);
    }

    protected function sendBatch($data): void
    {
        print($data);
    }
}

/**
 * Mocks global function extension_loaded to return the value
 * of global variable $extension_loaded
 */
function extension_loaded($extension)
{
    return $GLOBALS['extension_loaded'];
}

// phpcs:enable
